// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BitBucketSourceListerExpansion allows custom methods to be added to
// BitBucketSourceLister.
type BitBucketSourceListerExpansion interface{}

// BitBucketSourceNamespaceListerExpansion allows custom methods to be added to
// BitBucketSourceNamespaceLister.
type BitBucketSourceNamespaceListerExpansion interface{}
