required = [
  "k8s.io/apimachinery/pkg/util/sets/types",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "sigs.k8s.io/controller-runtime/pkg/client/config",
  "sigs.k8s.io/controller-runtime/pkg/controller",
  "sigs.k8s.io/controller-runtime/pkg/handler",
  "sigs.k8s.io/controller-runtime/pkg/manager",
  "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
  "sigs.k8s.io/controller-runtime/pkg/source",
  "github.com/knative/test-infra/scripts",
  "github.com/knative/test-infra/tools/dep-collector",
  "github.com/knative/build/pkg/apis/build/v1alpha1",
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "github.com/knative/test-infra"
  non-go = false

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[override]]
  name = "github.com/knative/pkg"
  # HEAD as of 2019-03-18
  revision = "915415e7be67bf8fb05249fe3f1bad25fcaf7f50"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "github.com/knative/serving"
  version = "v0.4.1"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=0.1.9"

[[constraint]]
  name = "github.com/knative/eventing-sources"
  version = "0.5.0"
