apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    eventing.knative.dev/source: "true"
  name: bitbucketsources.sources.eventing.knative.dev
spec:
  group: sources.eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: BitBucketSource
    plural: bitbucketsources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            consumerKey:
              properties:
                secretKeyRef:
                  type: object
              type: object
            eventTypes:
              items:
                enum:
                - repo:push
                - repo:fork
                - repo:updated
                - repo:commit_comment_created
                - repo:commit_status_created
                - repo:commit_status_updated
                - pullrequest:created
                - pullrequest:updated
                - pullrequest:approved
                - pullrequest:unapproved
                - pullrequest:fulfilled
                - pullrequest:rejected
                - pullrequest:comment_created
                - pullrequest:comment_updated
                - pullrequest:comment_deleted
                - issue:created
                - issue:updated
                - issue:comment_created
                type: string
              minItems: 1
              type: array
            ownerAndRepository:
              minLength: 1
              type: string
            consumerSecret:
              properties:
                secretKeyRef:
                  type: object
              type: object
            serviceAccountName:
              type: string
            sink:
              type: object
          required:
          - ownerAndRepository
          - eventTypes
          - consumerKey
          - consumerSecret
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    # we use a string in the stored object but a wrapper object
                    # at runtime.
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            sinkUri:
              type: string
            webhookUUIDKey:
              type: string
          type: object
  version: v1alpha1
