apiVersion: v1
kind: Service
metadata:
  name: bitbucket-controller
  namespace: knative-sources
  labels:
    control-plane: bitbucket-controller-manager
spec:
  selector:
    control-plane: bitbucket-controller-manager
  ports:
    - port: 443
